import re

pattern= r"[A-Z]+yclone"

text='''
Intense Tropical Cyclone Dumazile was a strong tropical cyclone that brought flooding to Madagascar and Réunion in early March 2018. Dumazile originated from an area of low pressure that formed in the South-West Indian Ocean near Agaléga on 27 February. The system concentrated into a tropical disturbance on 2 March and was named the next day, as it intensified into a tropical storm. Amid conditions conducive for intensification, Dumazile strengthened over the next two days and reached peak intensity on 5 March as an intense tropical cyclone, with 10-minute sustained winds of 165 km/h (105 mph), 1-minute sustained winds of 205 km/h (125 mph), and a central pressure of 945 hPa (27.91 inHg). The system weakened steadily over the next couple days because of increasing wind shear as it tracked to the southeast. Dumazile became post-tropical on 7 March and eventually dissipated completely on 10 March near the Kerguelen Islands.

Dyclone Dumazile affected Réunion less than two months after Cyclone Berguitta, halting ongoing repairs to bridges and reconstruction efforts. Torrential rainfall, reaching 1,600 mm (63 in) in Salazie, caused significant flooding across the island. Floodwaters, landslides, and downed trees caused significant damage and disruption to the road network on Réunion, particularly in coastal and mountainous areas. Repairs to the highway between Îlet Furçy and Cilaos were set back significantly. Large waves along the coast caused erosion, leading to collapses of beachfront infrastructure and beach closures. Ports were also damaged by the waves, and the Port of Saint-Gilles was clogged by debris. The agricultural sector incurred about €3 million (US$3.73 million; equivalent to $4.53 million in 2023) of damage, as crops were destroyed by floods and gusty winds. Recovery in Réunion was later hampered further by Cyclone Fakir in April.

The northern and eastern coasts of Madagascar experienced about 210 mm (8.3 in) of rain. Flooding occurred in Toamasina as a result of malfunctioning drainage systems which had been damaged by Cyclone Ava in January. Parts of the city lost power during the storm. Severe flooding in the Diana Region blocked roadways, inundated homes, and damaged crops. The RN6 highway in particular experienced several accidents and breakdowns, and a 18 m (59 ft) section of the road collapsed. Strong winds in coastal towns resulted in fallen trees, beach erosion, and damage to property and infrastructure. The Ambalavola District was left underwater, with sewage flowing through neighborhoods. Two people died in Madagascar during the storm: one in Ankorondrano and the other in Ambatoroka.
Dyclone Dyclone Dyclone Dyclone Dyclone
Meteorological history
A large region of unsettled weather along the Intertropical Convergence Zone spawned a broad area of low pressure in the South-West Indian Ocean near Agaléga on 27 February 2018.[1][2] The system became more concentrated and well-defined as it drifted between Agaléga and Tromelin Island,[3] leading Météo-France La Réunion (MFR) to classify it as a Zone of Disturbed Weather at 00:00 UTC on 1 March.[4][nb 1] That night increased thunderstorm activity in conjunction with an easterly wind burst furthered development,[6] and the MFR reported that the system became Tropical Disturbance 06 at 06:00 UTC on 2 March.[4] At the same time, the Joint Typhoon Warning Center (JTWC) classified the system as a tropical depression.[7][nb 2] The incipient disturbance underwent a small clockwise loop over the rest of 2 March, amid opposing steering flows from the north and south.[9] During that time the disturbance's organisation increased, with the development of a curved rainband. The MFR noted the surrounding atmospheric environment to be quite conducive to strengthening, with low wind shear, high relative humidity values, and pronounced outflow channels.[10] The JTWC stated that the system had become a tropical storm at 12:00 UTC on 2 March, as it began producing 1-minute sustained winds of 65 km/h (40 mph).[7] The MFR also upgraded the system to a tropical storm at 00:00 UTC on 3 March, based on scatterometer data, upon which it received the name Dumazile.[11]

refer to adjacent text
Map plotting the storm's track and intensity, according to the Saffir–Simpson scale
Map key
Modest strengthening ensued on 3 March as Dumazile began to move southwestward, in response to a developing ridge to its east. A pocket of dry air to Dumazile's west briefly weakened the thunderstorms covering the cyclone's low-level circulation center, but low wind shear allowed thunderstorms to quickly redevelop over the center.[12] Faster intensification began on 4 March, as the inner core began to tighten up and the radius of maximum wind decreased,[13] with the MFR upgrading Dumazile to a severe tropical storm by 06:00 UTC.[4] Microwave satellite imagery displayed a nascent eyewall on the evening of 4 March,[14] leading the MFR to assess that Dumazile had reached tropical cyclone strength by 18:00 UTC.[4] An eye became increasingly apparent as Dumazile turned south-southeastward, while rounding the periphery of the ridge to its east, coinciding with significant strengthening through the morning of 5 March.[15][16] By 12:00 UTC, Dumazile reached its peak intensity as an intense tropical cyclone, with 10-minute sustained winds of 165 km/h (105 mph), gusts up to 230 km/h (145 mph), and a minimum pressure of 945 hPa (27.91 inHg), as estimated by the MFR;[4] the JTWC concurrently estimated 1-minute sustained winds to have reached 205 km/h (125 mph).[7] Despite the cyclone's intensity, its eye remained somewhat oval in shape, likely due to interaction of the northwestern part of the circulation with the mountainous terrain of Madagascar.[16] Dumazile also made its closest approach to Réunion during 5 March, passing some 385 km (240 mi) from the island.[17]

Dumazile's peak was short-lived, as weakening began almost immediately, with an increase in northwesterly wind shear over the system associated with an upper-level trough.[18] The eye collapsed entirely on 6 March as Dumazile began interacting with the upper-level trough,[19] and the system fell back to severe tropical storm status by 18:00 UTC.[4] Thunderstorm activity quickly became confined to Dumazile's southeastern quadrant as a result of dry air and shear,[20] leading the MFR to declare that Dumazile had become post-tropical by 00:00 UTC on 7 March.[4] The JTWC classified Dumazile as a subtropical storm at 12:00 UTC.[7] Extratropical transition began later on 7 March, while Dumazile accelerated southeastward into the midlatitude westerlies.[21] The JTWC ceased tracking Dumazile at 18:00 UTC on 8 March;[7] the MFR continued to monitor Dumazile as it became fully extratropical at 06:00 UTC on 9 March. The remnant system was last noted by the MFR just north of the Kerguelen Islands a day later.[4]

Tropical cyclones passing close to Réunion in 2018, including Ava, Berguitta, Dumazile, and Fakir, caused a large reduction in the amount of mid- to upper-level clouds over the island.[22] A combination of the Madden–Julian oscillation and tropical cyclones Dumazile, Eliakim, and Fakir resulted in a westward flow of moisture, causing severe rainfall over Kenya during March and April 2018.[23][24][25]

Preparations, impact, and aftermath
Réunion
A cyclone pre-warning was issued for the island of Réunion on 4 March.[17] The cyclone pre-warning ended at 6:00 p.m. Réunion Time (14:00 UTC) on 5 March, as Dumazile veered away from the island. Schools and businesses remained closed through 6 March.[26][27][28] All schools reopened on 7 March, with the exception of several in Saint-Paul and Saint-Leu, where roadways were still blocked.[29] Torrential rainfall affected the island, a 24-hour total of 990 mm (39 in) occurring at Grand Îlet. The Volcanic Highway, La Plaine-des-Palmistes, and Cilaos all experienced significant rainfall during the same period.[17][30] Severe damage was inflicted to the road system on Réunion. Roads across the island experienced landslides, flooding, and downed trees.[31] East and westbound traffic traveling across the island was restricted to the Plaines highway, due to other roads flooding.[32]

The coastal and mountain highways were closed immediately following the storm.[28] A section of the mountain road was covered in debris after a landslide occurred and strong waves submerged four lanes of the coastal highway with seawater.[17] Approximately 150 mm (5.9 in) of rain fell on a cliff overlooking the coastal road, prompting an inspection before the road was able to reopen.[33] A large lake developed on the Plaine des Cafres, due to heavy rainfall.[32] Several bridges were either swept away or submerged by floodwaters, and several roads were flooded across Cilaos and Salazie.[34] The ReNovRisk project utilized three seismic stations in the Salazie Basin to measure microseismic data and determine the level of sediment transport down a river.[35] Landslides occurred in two neighborhoods of Brittany, and a wall collapsed in the mountainous region.[36] A landslide in the Piton Cailloux District, Sainte-Marie, isolated around 10 families.[37]

High waves along the shore decimated boats in the port of Sainte-Marie. The Roches Noires beach was completely submerged in water.[17] A fence and the northern access to an esplanade at the beach collapsed.[38] Significant portions of sand were washed away from the beach, exposing the foundations of the esplanade.[39] The MNS beach surveillance station and three masts used for signalling sustained damage. As a result, the lifeguard station was closed and rescues were no longer possible.[40][41] Tarpaulins covering crops on the Cisaille Plateau were ripped off. All the crops near Salazie were destroyed after 1,600 mm (63 in) of rain fell.[42] New crops planted after Cyclone Berguitta were destroyed, leading to shortages of fruits and vegetables.[43] Agricultural damage on Réunion was €3 million (US$3.73 million; equivalent to $4.53 million in 2023[44]).[45] Trees fell at two nursery schools in Saint-Denis.[36] A boil-water advisory was issued for Saint-Joseph. Portions of Salazie were left without potable water. In the municipality of Saint Benoit, interruptions in the water supply were expected by authorities following a power outage.[46] Low-lying areas in the Chaudron neighborhood, Sainte-Clotilde, flooded during the storm.[47] Temporary barriers in Tampon were stolen during the storm; the barriers were found in a ditch.[48]

The Saint-Gilles port had to be unblocked as a result of debris and damage left behind.[17][30] Repair work on the Cilaos bridge was halted, due to severe conditions during the storm. Residents erected a temporary bridge using ladders to rescue 400 marooned people elsewhere in Cilaos and another 100 on a beach near Îlet Furçy.[49] A trail from Bois Court and Grand Bassin was closed as a result of damage inflicted by cyclones Berguitta and Dumazile. Cliff repair work was scheduled for March, with a planned reopening date in April.[50] The Dos d'Ane–Deux Bras hiking trail reopened on 17 July, after suffering damage during cyclones Berguitta, Dumazile, and Fakir.[51] The RN5 highway was impassable for months at Îlet Furçy, after cyclones Ava, Berguitta, and Dumazile caused several landslides. Work to rebuild two bridges damaged during the storm, a project costing around €100 million (US$121.1 million; equivalent to $146.94 million in 2023[44]), was halted after a prosecutor threatened criminal charges against officials for violating laws prohibiting circulating machinery from being in the Saint-Etienne river. Around 1,500 people protested the halt of the construction project.[52][53] The RN5 highway later reopened; multiple projects were proposed in December 2020 to further safeguard the highway from the effects of weather events. These proposals occurred as a result of the 2018 shutdown's long duration.[54] Authorities in Saint-Paul municipality worked to create a barrier made of boulders,[38] repair an observation deck, and repair ramps leading to the Roches Noires beach. The project was estimated to cost about €46,000 (US$56,000; equivalent to $68,000 in 2023[44]).[39] Access to the beach was prohibited from 19 March to 6 April, as a precautionary measure to prevent injuries.[55] Approximately €2.3 million in aid (US$2.8 million; equivalent to $3.4 million in 2023[44]) was released to farmers who suffered losses during cyclones Berguitta, Dumazile, and Fakir.[56]

Madagascar
Due to the threat of severe weather in Madagascar, a yellow alert was issued for the regions of Analanjirofo, Atsinanana, Diana, Sava, and Sofia, as well as the Farafangana, Nosy Varika, Manakara, Mananjary, Vohipeno,[57][58] and Mahajanga districts.[59] Heavy rain and red alerts were later issued for the regions of Diana, Bealanana, Antalaha, Antsohihy, and Mahajanga I and II.[60][61][62] A blue alert was issued for the Analanjirofo, Atsinanana, and Sava regions as Dumazile moved away from Madagascar.[61][63] Approximately 210 mm (8.3 in) of rain accumulated across the northeastern coast of Madagascar. NASA's Global Precipitation Measurement satellite recorded rainfall rates of 160 mm (6.3 in) per hour in the region with its Dual Frequency Precipitation Radar. Rates of 216 mm (8.5 in) per hour were recorded in a rainband located off the coast.[64] One-day rainfall amounts of 100–150 mm (3.9–5.9 in) and 250 mm (9.8 in) occurred across the northern and eastern coasts, respectively. A peak 48-hour rainfall total of 356 mm (14.0 in) was recorded at the Plaine des Palmistes.[65] Yellow alerts were issued for the Manampatrana and Matitanana rivers as water levels neared critical levels.[66]

Portions of Toamasina flooded during the storm, as a result of malfunctioning drainage systems that were damaged during Cyclone Ava.[57] Knee-deep flooding was reported in multiple areas.[67] The Mangarano, Andranomadio, Tanambao II, and Ankirihiry districts of the city were submerged by floodwaters.[68] Dumazile caused power outages in Toamasina on 4 March, sparking an incident in which University of Toamasina students burned tires and damaged three passing cars were with rocks.[69][70] Homes, an internet café, and vendors were looted and vandalized. At least 19 students were detained by authorities;[69][71] four of the students were later expelled from the university.[72] The city's port suffered delays during the passage of the storm.[73] Strong winds and heavy rains damaged homes, light poles, and metal sheeting from Toamasina to Ste Marie.[74]

The Diana Region experienced torrential rainfall, inundating the lower regions of Nosy Be island with floodwaters and rendering some areas inaccessible.[75][60] The Nosy Be police department halted maritime travel between Île aux Parfums and the Ankify port.[75] Officials called for the evacuation of areas that normally flood or had already flooded.[60] Two shelters were established in Ampasindava and Dzamandzar for victims of the storm.[76] Rivers spilled their banks in Ambanja and Ambilobe, flooding homes and fields. The swollen streams overtook bridges and made roadways impassable.[75] Embankments were at risk of failure.[60] Excessive rainfall resulted in accidents and vehicle breakdowns on the RN6 highway, including a truck that blocked the road near Isesy, preventing the passage of 20 other trucks. Strong winds felled trees, damaged crops, eroded beaches, and damaged homes and public infrastructure in coastal towns. The Ambalavola District was left underwater, with solid and liquid waste from septic tanks flowing through neighborhoods.[75] A man died after falling into the Andriantany Canal in Ankorondrano. In Ambatoroka, a man slipped and hit his head on a rock during the storm, later dying from his injuries.[77] The CISCO[nb 3] schools in Ambanja, Ambilobe, Nosy-Be, and Toamasina II, and the ZAP[nb 4] schools in Mananjary and Nosy Varika were suspended as a result of high water.[60] As Dumazile tracked away from Madagascar, maritime traffic along the eastern coastline was prohibited by authorities.[79]

Residents in Toamasina chose to remain in their homes instead of evacuating to shelters in an effort to protect their property. The local government was criticised for its slow response in providing aid to victims of the storm.[68] The Ambilobe-Antsiranana road (RN6) reopened on 13 March, after suffering flood damage during the storm. A temporary, 20 m (66 ft) Bailey bridge was installed in Isesy to reopen the road to traffic after an 18 m (59 ft) section of the road slumped. The closure of the RN6 highway cut off gasoline shipments to Antsiranana. Long lines persisted for days outside gas stations as fuel became scarce; gasoline was rationed for safety reasons, to prevent storage in inappropriate containers. Electrical grids in the area experienced shortages, and basic supplies ran low
Topics in the news
Ebrahim Raisi in 2023
Ebrahim Raisi
The European Union passes the Artificial Intelligence Act, aiming to establish a regulatory and legal framework for AI.
A helicopter crash near Varzaqan, Iran, kills eight people, including President Ebrahim Raisi (pictured) and Foreign Minister Hossein Amir-Abdollahian.
In boxing, Oleksandr Usyk defeats Tyson Fury to become the first undisputed heavyweight champion in twenty-four years.
Protests over voting rights changes break out in the French territory of New Caledonia.
Ongoing: Israel–Hamas war timelineRussian invasion of Ukraine timelineWar in Sudan timeline
Recent deaths: KabosuIvan BoeskyNarayanan VaghulDavid WilkieFernando Martínez CastellanoJohn Koerner
'''
# match=re.search(pattern, text)
# print(match)

matchs=re.finditer(pattern, text)
for match1 in matchs:
    print("\n",match1)
    print(match1.span())
    print(text[match1.span()[0]:match1.span()[1]])
    print(type(match1.span()))